#!/bin/bash
#**********************************************************************
#***                                                                ***
#*** Script:  mvs                                                   ***
#***                                                                ***
#*** Purpose: IPL OS/VS2-MVS 3.8j (TK4- unattended operations)      ***
#***                                                                ***
#*** Updated: 2014/12/22                                            ***
#***                                                                ***
#**********************************************************************
#
# set environment
#
a=`uname -m`
echo "a=${a}"
if [[ ${a} == 'aarch64' ]];then
   arch='arm'
else if [[ $a == 'x86_64' ]];then arch=64;else arch=32;fi;fi
echo "arch=$arch"
system=linux
export LD_LIBRARY_PATH=/opt/tk4/hercules/$system/$arch/lib:/opt/tk4/hercules/$system/$arch/lib/hercules:$LD_LIBRARY_PATH
MODE=`head -1 /opt/tk4/unattended/mode 2>/dev/null`
#
# source configuration variables
#
if [ -f /opt/tk4/local_conf/tk4-.parm ]; then . /opt/tk4/local_conf/tk4-.parm; fi
if [[ ${arch:0:3} == 'arm'   && $REP101A == '' ]];then export REP101A=specific;fi
if [[ $REP101A == 'specific' && $CMD101A == '' ]];then export CMD101A=02;fi
#
# IPL OS/VS2-MVS 3.8j
#
export HERCULES_RC=/opt/tk4/scripts/ipl.rc
/opt/tk4/hercules/linux/arm/bin/hercules -d -f /opt/tk4/conf/tk4-.cnf >/opt/tk4/log/3033.log