#!/bin/bash

if [ -z "$(/bin/ls -A /opt/tk4/dasd)" ]; then
  echo "Setting up DASD directory on persistent volume claim."
  cp -rfv /opt/tk4/dasd.source/* /opt/tk4/dasd/
else
  echo "DASD directory already setup."
fi